# Generated by Django 4.2.26 on 2025-12-24 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectjson',
            name='html',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='projectjson',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='builder.project'),
        ),
    ]
