# Generated by Django 4.2.26 on 2026-02-21 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email')], default='EMAIL', max_length=30)),
                ('purpose', models.CharField(choices=[('SEND_TOKEN', 'Send Token'), ('VERIFY_EMAIL', 'Verify Email')], max_length=50)),
                ('challenge_hash', models.CharField(help_text='Hashed token only', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('provider', models.CharField(max_length=50)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=512)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('source', models.CharField(default='web', help_text='web / api / worker', max_length=50)),
                ('request_type', models.CharField(help_text='auth / data / admin / internal', max_length=50)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'request_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='request_log_created_4f2782_idx'), models.Index(fields=['email'], name='request_log_email_70c1d2_idx'), models.Index(fields=['request_type'], name='request_log_request_1ece74_idx'), models.Index(fields=['status_code'], name='request_log_status__5a9c0b_idx')],
            },
        ),
    ]
