# Generated by Django 4.2.26 on 2025-12-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_project_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectjson',
            name='html',
            field=models.TextField(default=''),
        ),
    ]
