# Generated by Django 4.2.26 on 2025-12-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_projectjson_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectjson',
            name='html',
            field=models.TextField(default='', null=True),
        ),
    ]
