# Generated by Django 4.2.26 on 2025-12-24 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectjson',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='builder.project'),
        ),
    ]
