# Generated by Django 4.2.26 on 2025-12-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_alter_projectjson_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
