# Generated by Django 4.2.26 on 2025-12-25 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0007_alter_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectjson',
            name='html',
        ),
    ]
